<?php

return [
    // "Breadcrumbs" priekš katras lapas teksta, kas ir redzams parlūka logā "tab"
    'breadcrumb.dashboard' => 'Dashboard',
    'breadcrumb.about' => 'About us',
    'breadcrumb.contacts' => 'Contacts',
    'breadcrumb.groups' => 'Groups',
    'breadcrumb.groups.show' => 'Show group',
    'breadcrumb.groups.edit' => 'Edit group',
    'breadcrumb.groups.create' => 'Create Group',
    'breadcrumb.users' => 'Users',
    'breadcrumb.users.assign' => 'Assign role',
    'breadcrumb.users.create' => 'User create',
    'breadcrumb.users.edit' => 'Edit user',
    'breadcrumb.users.show' => 'User details',
    'breadcrumb.employees' => 'Employees',
    'breadcrumb.roles' => 'Roles',
    'breadcrumb.roles.create' => 'Create roles',
    'breadcrumb.roles.edit' => 'Edit role',
    'breadcrumb.roles.show' => 'Show role',
    'breadcrumb.maps' => 'Maps',
    'breadcrumb.maps.edit' => 'Edit map',
    'breadcrumb.languages' => 'Languages',
    'breadcrumb.languages.translations' => 'Translations',
    'breadcrumb.languages.create' => 'Create',
    'breadcrumb.languages.edit' => 'Edit',
    'breadcrumb.settings.profile' => 'Profile settings',
    'breadcrumb.settings.business' => 'Business settings',
    'breadcrumb.settings.password' => 'Password settings',
    'breadcrumb.settings.clocking' => 'Auto clock settings',
    'breadcrumb.settings.appearance' => 'Appearance settings',
    'breadcrumb.settings.language' => 'Language settings',

    // Sānu navigācijas joslu  iespējas
    'sidebar.label' => 'Navigation',
    'sidebar.dashboard' => 'Dashboard',
    'sidebar.employees' => 'Employees',
    'sidebar.groups' => 'Groups',
    'sidebar.users' => 'Users',
    'sidebar.roles' => 'Roles',
    'sidebar.map' => 'Map',
    'sidebar.languages' => 'Languages',
    'sidebar.about' => 'About us',
    'sidebar.contacts' => 'Contacts',

    'sidebar.settings.profile' => 'Profile',
    'sidebar.settings.business' => 'Business',
    'sidebar.settings.password' => 'Password',
    'sidebar.settings.clocking' => 'Auto clocking',
    'sidebar.settings.appearance' => 'Appearance',
    'sidebar.settings.language' => 'Language',
    'sidebar.settings.title' => 'Settings',
    'sidebar.settings.description' => 'Manage your profile and account settings',

    // Lietotāja izvēles opcijas
    'menu.settings' => 'Settings',
    'menu.out' => 'Log out',

    // Uzņēmumu izvēle, kas ir redzama tikai "Owner" lomai
    'dropdown.select.business' => '- select business -',
    'dropdown.select.business.title' => 'Businesses',

    // Viss, kas saistīts ar iestatījumiem
    'settings.profile.success.update' => 'Profile updated successfully!',
    'settings.profile.success.portrait' => 'Portrait updated successfully!',
    'settings.profile.success.portrait.remove' => 'Portrait removed successfully!',

    'settings.profile.remove' => 'Remove',
    'settings.profile.remove.confirm' => 'Remove portrait?',
    'settings.profile.id' => 'ID',
    'settings.profile.age' => 'Age',
    'settings.profile.code' => 'Personal code',
    'settings.profile.phone' => 'Phone',
    'settings.profile.title' => 'Profile settings',
    'settings.profile.small.title' => 'Profile information',
    'settings.profile.small.description' => 'Update your personal details and contact information',
    'settings.profile.name' => 'Name',
    'settings.profile.email' => 'Email',
    'settings.profile.height' => 'Height (Cm)',
    'settings.profile.weight' => 'Weight (Kg)',
    'settings.profile.country' => 'Country',
    'settings.profile.city' => 'City',
    'settings.profile.save' => 'Save',

    'settings.profile.delete.title' => 'Delete account',
    'settings.profile.delete.description' => 'Delete your account and all of its resources',
    'settings.profile.delete.warning' => 'Warning',
    'settings.profile.delete.text' => 'Please proceed with caution, this cannot be undone',
    'settings.profile.delete.dialog.delete' => 'Delete account',
    'settings.profile.delete.dialog.title' => 'Are you sure you want to delete your account?',
    'settings.profile.delete.dialog.description' => 'Once your account is deleted, all of its resources and data will also be permanently deleted. Please enter your password to confirm you would like to permanently delete your account',
    'settings.profile.delete.dialog.password' => 'Password',
    'settings.profile.delete.dialog.cancel' => 'Cancel',
    'settings.profile.delete.dialog.delete.confirm' => 'Delete account',

    'settings.business.success.update' => 'Business updated successfully!',
    'settings.business.success.logo' => 'Logo updated successfully!',
    'settings.business.success.logo.remove' => 'Logo removed successfully!',

    'settings.business.title' => 'Business settings',
    'settings.business.small.title' => 'Business information',
    'settings.business.small.description' => 'Update your business details, contact info, and logo',
    'settings.business.empty' => 'No business profile found',
    'settings.business.empty.text' => 'Create one to view details here',
    'settings.business.remove' => 'Remove logo?',
    'settings.business.remove.confirm' => 'Remove',
    'settings.business.phone' => 'Phone',
    'settings.business.adress' => 'Address',
    'settings.business.city' => 'City',
    'settings.business.country' => 'Country',
    'settings.business.name' => 'Name',
    'settings.business.industry' => 'Industry',
    'settings.business.email' => 'Email',
    'settings.business.description' => 'Brief description',
    'settings.business.save' => 'Save',
    'settings.business.create' => 'Create',

    'settings.business.locked.title' => 'Business creation locked',
    'settings.business.locked.label' => 'Business creation locked',
    'settings.business.locked.text.1' => 'You are currently working for a business. You cannot create a business until you are removed from this business',
    'settings.business.locked.text.2' => 'Ask the owner of the business to remove you, if you wish to be a business owner',
    'settings.business.locked.back' => 'Back',

    'settings.password.success.update' => 'Password updated successfully!',

    'settings.password.title' => 'Password settings',
    'settings.password.small.title' => 'Update password',
    'settings.password.small.description' => 'Ensure your account is using a long, random password to stay secure',
    'settings.password.current' => 'Current password',
    'settings.password.new' => 'New password',
    'settings.password.confirm' => 'Confirm new password',
    'settings.password.save' => 'Save',

    'settings.clocking.success.update' => 'Settings updated successfully!',
    'settings.clocking.success.extend' => 'Settings updated successfully!',
    'settings.clocking.success.in' => 'You got clocked in successfully!',

    'settings.clocking.title' => 'Auto clock settings',
    'settings.clocking.small.title' => 'Auto clock settings',
    'settings.clocking.small.description' => 'Adjust the times when you recieve reminders',
    'settings.clocking.work.start' => 'Work start',
    'settings.clocking.work.end' => 'Work end',
    'settings.clocking.lunch.start' => 'Lunch start',
    'settings.clocking.lunch.end' => 'Lunch end',
    'settings.clocking.clear' => 'Clear lunch',
    'settings.clocking.save' => 'Save',

    'settings.clocking.extend.label' => 'Extend work time',
    'settings.clocking.extend.description' => 'To extend your work time (up to 12 hours max) use minutes',
    'settings.clocking.extend.save' => 'Save',

    'settings.clocking.locked.title' => 'Auto-clock settings locked',
    'settings.clocking.locked.label' => 'Access restricted',
    'settings.clocking.locked.text.1' => 'You must belong to a business if you wish to use these settings',
    'settings.clocking.locked.text.2' => 'Get a job!',
    'settings.clocking.locked.back' => 'Back',

    'settings.appearance.small.title' => 'Appearance settings',
    'settings.appearance.title' => 'Appearance settings',
    'settings.appearance.small.description' => 'Update your accounts appearance settings',
    'settings.appearance.light' => 'Light',
    'settings.appearance.dark' => 'Dark',
    'settings.appearance.system' => 'System',

    'settings.language.title' => 'Language',
    'settings.language.small.title' => 'Language settings',
    'settings.language.small.description' => 'Select your preferred language',
    'settings.language.search' => 'Search',
    'settings.language.empty' => 'No languages found',
    'settings.language.default' => '(default)',
    'settings.language.active' => 'Active',

    // "Dashboard" un viss kas ir redzams tajā
    'dashboard.view.title' => 'Dashboard',

    'dashboard.diagrams.range.week' => 'Week',
    'dashboard.diagrams.range.month' => 'Month',

    'dashboard.diagrams.weekday.1' => 'Monday',
    'dashboard.diagrams.weekday.2' => 'Tuesday',
    'dashboard.diagrams.weekday.3' => 'Wednesday',
    'dashboard.diagrams.weekday.4' => 'Thursday',
    'dashboard.diagrams.weekday.5' => 'Friday',
    'dashboard.diagrams.weekday.6' => 'Saturday',
    'dashboard.diagrams.weekday.7' => 'Sunday',

    'dashboard.diagrams.employees.activity.empty' => 'Get a job, to view personal statistics',
    'dashboard.diagrams.employees.activity.title' => 'Activity',
    'dashboard.diagrams.employees.activity.tooltip' => 'Employees',

    'dashboard.diagrams.messages.empty' => 'Get a job, or ask to be added to a group, to view messages',
    'dashboard.diagrams.messages.status.new' => 'New activity',
    'dashboard.diagrams.messages.status.none' => 'No unread messages',

    'dashboard.diagrams.overview.empty' => 'Get a job, to view this panel',
    'dashboard.diagrams.overview.personal.status.in' => 'Currently working',
    'dashboard.diagrams.overview.personal.status.out' => 'Not working',
    'dashboard.diagrams.overview.personal.action.out' => 'Clock out',
    'dashboard.diagrams.overview.personal.action.in' => 'Clock in',
    'dashboard.diagrams.overview.business.status' => 'Last seen',
    'dashboard.diagrams.overview.business.title' => 'Employees',

    'dashboard.diagrams.hours.empty' => 'Get a job, to view personal statistics',
    'dashboard.diagrams.hours.title' => 'Worked hours',
    'dashboard.diagrams.hours.name' => 'Hours',

    // Darbinieku pievienošanas skats
    'employees.error.auth.in' => 'You do not have permission to clock in this user!',
    'employees.error.auth.out' => 'You do not have permission to clock out this user!',
    'employees.error.auth.add' => 'You do not have permission to add employees!',
    'employees.error.auth.remove' => 'You do not have permission to remove employees!',

    'employees.error.nothing' => 'Nothing found!',
    'employees.error.missing' => 'Select a business to add to!',
    'employees.error.in' => 'You are already clocked in!',
    'employees.error.out' => 'You are not clocked in!',
    'employees.error.add' => 'This user cannot be added as an employee!',
    'employees.error.different' => 'This user already belongs to a different business!',
    'employees.error.belongs' => 'This user is already an employee of this business!',

    'employees.success.in' => 'You clocked in successfully!',
    'employees.success.out' => 'You clocked out successfully!',
    'employees.success.add' => 'Employee added successfully!',
    'employees.success.remove' => 'Employee removed successfully!',

    'employees.index.total' => 'Total employees',
    'employees.index.title' => 'Employees',
    'employees.index.label' => 'Employees',
    'employees.index.id' => 'ID',
    'employees.index.name' => 'Name',
    'employees.index.time' => 'Clocked in',
    'employees.index.actions' => 'Actions',
    'employees.index.remove' => 'Remove',
    'employees.index.in' => 'Clock-in',
    'employees.index.out' => 'Clock-out',
    'employees.index.empty' => 'No employees found',
    'employees.index.text' => 'Manage employees and track their working time',

    'employees.search.label' => 'Add new employee',
    'employees.search.description' => 'Add or remove employees, check their activity',
    'employees.search.search' => 'Search',
    'employees.search.add' => 'Add',

    // Grupu skats un viss, kas saistīts ar to
    'groups.success.create' => 'Group created successfully!',
    'groups.success.update' => 'Group updated successfully!',
    'groups.success.delete' => 'Group deleted successfully!',
    'groups.success.attach' => 'Map attached successfully!',
    'groups.success.detach' => 'Map detached successfully!',
    'groups.success.upload' => 'Image uploaded successfully!',
    'groups.success.remove' => 'Image removed successfully!',

    'groups.success.users.add' => 'Users added to group successfully!',
    'groups.success.users.remove' => 'User removed from group successfully!',

    'groups.show.users.add.label' => 'Select users',
    'groups.show.users.add.cancel' => 'Cancel',
    'groups.show.users.add.add' => 'Add',

    'groups.show.users.add' => 'Add',
    'groups.show.users.label' => 'Users',
    'groups.show.users.remove' => 'Remove',

    'groups.show.images.label' => 'Upload new image',
    'groups.show.images.upload' => 'Upload',
    'groups.show.images.delete' => 'Delete',
    'groups.show.images.empty' => 'No images uploaded yet',

    'groups.show.maps.detach' => 'Detach',
    'groups.show.maps.label' => 'Select a map',
    'groups.show.maps.add' => 'Add',
    'groups.show.maps.empty' => 'No map attached',

    'groups.index.title' => 'Groups',
    'groups.index.label' => 'Groups',
    'groups.index.text' => 'Manage and organize your groups efficiently',
    'groups.index.create' => 'Create',
    'groups.index.id' => 'ID',
    'groups.index.name' => 'Name',
    'groups.index.description' => 'Description',
    'groups.index.business' => 'Business',
    'groups.index.actions' => 'Actions',
    'groups.index.show' => 'Show',
    'groups.index.edit' => 'Edit',
    'groups.index.delete' => 'Delete',
    'groups.index.empty' => 'No groups found',

    'groups.show.title' => 'Group',
    'groups.show.text' => 'Manage members, images, and map entries for this group',
    'groups.show.back' => 'Back',
    'groups.show.description' => 'No description provided',
    'groups.show.overview' => 'Overview',
    'groups.show.business' => 'Business',
    'groups.show.users' => 'Users',
    'groups.show.chat' => 'Chat',
    'groups.show.images' => 'Images',
    'groups.show.maps' => 'Map',

    'groups.edit.title' => 'Edit group',
    'groups.edit.label' => 'Edit group',
    'groups.edit.text' => 'Update the groups name and description',
    'groups.edit.back' => 'Back',
    'groups.edit.name' => 'Name',
    'groups.edit.description' => 'Description',
    'groups.edit.save' => 'Save',

    'groups.create.title' => 'Create a Group',
    'groups.create.label' => 'Create group',
    'groups.create.text' => 'Add a new group and assign it to a business',
    'groups.create.back' => 'Back',
    'groups.create.name' => 'Name',
    'groups.create.description' => 'Description',
    'groups.create.save' => 'Save',

    // Lietotāji un viss, kas saistīts ar tiem
    'users.success.assign' => 'Role assigned successfully!',
    'users.success.store' => 'User created successfully!',
    'users.success.update' => 'User updated successfully!',
    'users.success.delete' => 'User deleted successfully!',

    'users.index.business.none' => 'No business',

    'users.index.status.active' => 'Active',
    'users.index.status.inactive' => 'Inactive',
    'users.index.status.business' => 'Business',

    'users.roles.global' => 'Global roles',
    'users.roles.business' => 'Business roles',
    'users.roles.assign' => 'Assign',

    'users.create.name' => 'Name',
    'users.create.email' => 'Email',
    'users.create.password' => 'Password',
    'users.create.create' => 'Create',

    'users.edit.name' => 'Name',
    'users.edit.email' => 'Email',
    'users.edit.password' => 'Password',
    'users.edit.save' => 'Save',

    'users.index.name' => 'Name',
    'users.index.business' => 'Business',
    'users.index.role' => 'Role',
    'users.index.status' => 'Status',
    'users.index.actions' => 'Actions',
    'users.index.assign' => 'Assign',
    'users.index.show' => 'Show',
    'users.index.edit' => 'Edit',
    'users.index.delete' => 'Delete',
    'users.index.empty' => 'No users found',
    'users.index.title' => 'Users',
    'users.index.label' => 'Users',
    'users.index.text' => 'A list of all the users including their business and role',
    'users.index.add' => 'Add',

    'users.profile.age' => 'Age',
    'users.profile.height' => 'Height (cm)',
    'users.profile.weight' => 'Weight (kg)',
    'users.profile.phone' => 'Phone',
    'users.profile.code' => 'Personal Code',
    'users.profile.country' => 'Country',
    'users.profile.city' => 'City',
    'users.profile.save' => 'Save',

    'users.assign.title' => 'Assign role',
    'users.assign.label' => 'Assign a role',
    'users.assign.description' => 'Assigning a role will allow the user to perform certain actions',
    'users.assign.back' => 'Back',

    'users.create.title' => 'Create user',
    'users.create.label' => 'Create user',
    'users.create.text' => 'Create a new account, then go to edit to complete it',
    'users.create.back' => 'Back',
    'users.create.info' => 'Account information',

    'users.edit.title' => 'Edit user',
    'users.edit.label' => 'Edit',
    'users.edit.text' => 'Edit an account and after that edit or add extended information',
    'users.edit.back' => 'Back',
    'users.edit.info' => 'Account information',
    'users.edit.profile.info' => 'Profile information',

    'users.show.title' => 'User',
    'users.show.label' => 'User details',
    'users.show.text' => 'Detailed information about this user',
    'users.show.business' => 'Business',
    'users.show.role' => 'Role',
    'users.show.phone' => 'Phone',
    'users.show.code' => 'Personal code',
    'users.show.age' => 'Age',
    'users.show.height' => 'Height (Cm)',
    'users.show.weight' => 'Weight (Kg)',
    'users.show.country' => 'Country',
    'users.show.city' => 'City',
    'users.show.back' => 'Back',

    // Lietotāju lomas un viss, kas saistīts ar tām
    'roles.error.exists' => 'Role name already exists!',
    'roles.error.auth' => 'You do not have permission to access this page!',
    
    'roles.success.create' => 'Role created successfully!',
    'roles.success.update' => 'Role updated successfully!',
    'roles.success.delete' => 'Role deleted successfully!',

    'roles.index.title' => 'Roles',
    'roles.index.id' => 'ID',
    'roles.index.name' => 'Name',
    'roles.index.permissions' => 'Permissions',
    'roles.index.business' => 'Business',
    'roles.index.actions' => 'Actions',
    'roles.index.show' => 'Show',
    'roles.index.edit' => 'Edit',
    'roles.index.delete' => 'Delete',
    'roles.index.label' => 'Roles',
    'roles.index.text' => 'Manage system roles and their assigned permissions',
    'roles.index.create' => 'Create',

    'roles.create.name' => 'Name',
    'roles.create.permissions' => 'Permissions',
    'roles.create.save' => 'Save',
    'roles.create.title' => 'Create Role',
    'roles.create.label' => 'Create role',
    'roles.create.text' => 'Create a new role and assign its permissions',
    'roles.create.back' => 'Back',
    
    'roles.edit.name' => 'Role',
    'roles.edit.permissions' => 'Permissions',
    'roles.edit.save' => 'Save',
    'roles.edit.title' => 'Edit role',
    'roles.edit.label' => 'Edit role',
    'roles.edit.text' => 'Modify the role name and adjust its assigned permissions',
    'roles.edit.back' => 'Back',

    'roles.show.title' =>  'Role',
    'roles.show.label' => 'Role details',
    'roles.show.text' => 'View detailed information and assigned permissions for this role',
    'roles.show.back' => 'Back',
    'roles.show.name' => 'Name',
    'roles.show.permissions' => 'Permissions',

    // Kartes lapa un viss, kas saistīts ar to
    'maps.name' => 'Name',
    'maps.name.none' => 'No name',

    'maps.error.auth' => 'You do not have permission to access this page!',
    'maps.error.polygon' => 'Polygon must have at least 3 points!',

    'maps.success.create' => 'Map created successfully!',
    'maps.success.update' => 'Map updated successfully!',
    'maps.success.delete' => 'Map deleted successfully!',

    'maps.edit.polygon' => 'Polygon',
    'maps.edit.title' => 'Edit map',
    'maps.edit.label' => 'Edit',
    'maps.edit.text' => 'You can edit by replacing the old shape or changing the data values',
    'maps.edit.lat' => 'Latitude',
    'maps.edit.lng' => 'Longitude',
    'maps.edit.radius' => 'Radius',
    'maps.edit.back' => 'Back',
    'maps.edit.name' => 'Name',
    'maps.edit.save' => 'Save',

    'maps.index.title' => 'Maps',
    'maps.index.label' => 'Map',
    'maps.index.text' => 'View, edit, and manage youre maps',
    'maps.index.loading' => 'Loading map',
    'maps.index.empty' => 'No maps found',
    'maps.index.id' => 'ID',
    'maps.index.name' => 'Name',
    'maps.index.created' => 'Created at',
    'maps.index.actions' => 'Actions',
    'maps.index.show' => 'Show',
    'maps.index.edit' => 'Edit',
    'maps.index.delete' => 'Delete',

    'maps.show.title' => 'Map',
    'maps.show.label' => 'Map',
    'maps.show.text' => 'Examine what you have placed',
    'maps.show.back' => 'Back',
    'maps.show.name' => 'Name',
    'maps.show.empty' => 'No name provided',
    'maps.show.type' => 'Type',
    'maps.show.created' => 'Created',

    // Valodu skats, kas ir tikai redzams ar lomu "Owner"
    'languages.error.progress' => 'Translation in progress, please wait!',

    'languages.success.create' => 'Language created successfully!',
    'languages.success.update' => 'Language updated successfully!',
    'languages.success.delete' => 'Language deleted successfully!',
    'languages.success.sync' => 'Synchronization started, please wait!',

    'languages.index.title' => 'Languages',
    'languages.index.label' => 'Languages',
    'languages.index.add' => 'Add',
    'languages.index.search' => 'Search languages',
    'languages.index.name' => 'Name',
    'languages.index.code' => 'Code',
    'languages.index.actions' => 'Actions',
    'languages.index.empty' => 'No languages found',
    'languages.index.sync' => 'Synchronize',
    'languages.index.edit' => 'Edit',
    'languages.index.delete' => 'Delete',

    'languages.edit.title' => 'Edit language',
    'languages.edit.label' => 'Edit language',
    'languages.edit.text' => 'Update the language name and code',
    'languages.edit.name' => 'Name',
    'languages.edit.code' => 'Code',
    'languages.edit.back' => 'Back',
    'languages.edit.save' => 'Save',

    'languages.create.title' => 'Create language',
    'languages.create.label' => 'Create language',
    'languages.create.text' => 'Create a new language for other people to understand',
    'languages.create.name' => 'Name',
    'languages.create.code' => 'Code',
    'languages.create.back' => 'Back',
    'languages.create.create' => 'Create',

    'translations.success.update' => 'Translation updated successfully!',

    'translations.index.group.all' => 'All view groups',
    'translations.index.view.all' => 'All views',
    'translations.index.field.all' => 'All details',
    'translations.index.search' => 'Search translations',
    'translations.index.key' => 'Key',
    'translations.index.original' => 'Original',
    'translations.index.translation' => 'Translation',
    'translations.index.actions' => 'Actions',
    'translations.index.empty' => 'Nothing was found',
    'translations.index.edit' => 'Edit',
    'translations.index.title' => 'Translations',
    'translations.index.label' => 'translations',
    'translations.index.back' => 'Back',
    'translations.index.more' => 'Load more',

    'translations.edit.title' => 'Edit translation',
    'translations.edit.label' => 'Edit translation',
    'translations.edit.key' => 'Key',
    'translations.edit.original' => 'Original text',
    'translations.edit.translation' => 'Translation',
    'translations.edit.back' => 'Back',
    'translations.edit.save' => 'Save',

    // Par mums lapa
    'about.why' => 'Why Choose Us?',
    'about.why.text' => 'Because we are trying to be the best at what we do and we keeps progressing towards the future',
    'about.mission' => 'What is our mission?',
    'about.mission.text' => 'Our mission is to provide small and even large bussineses with the best worker management application you can find on the internet that is totally for free',
    'about.value' => 'What do we value?',
    'about.value.text' => 'We value the time user spends using our application and we always look forward to improve the user experience, thats why we need your precious feedbacks!',

    // Kontaktu lapa
    'contacts.title' => 'Contacts',
    'contacts.label' => 'Contacts page',
    'contacts.support' => 'Customer support',
    'contacts.emails' => 'Official emails',
    'contacts.data' => 'Data protection specialist',

    // Sākuma lapa
    'welcome.dashboard.link' => 'Dashboard',
    'welcome.login.link' => 'Log in',
    'welcome.register.link' => 'Register',
    'welcome.view.welcome' => 'Lets get started',
    'welcome.view.text' => 'Check-In was made to make managing workers and projects easier',
    'welcome.view.list' => 'We suggest starting with the following',
    'welcome.view.list.1' => 'Fill in all the information about youreself',
    'welcome.view.list.2' => 'Then get to know the app and its features',

    // Viss, kas saistīts ar autentifikāciju, paroles atgūšanu un e-pasta verificēšanu
    'auth.forgot.small.title' => 'Forgot password',
    'auth.forgot.small.description' => 'Enter your email to receive a password reset link',
    'auth.forgot.title' => 'Forgot password',
    'auth.forgot.label' => 'Email address',
    'auth.forgot.button' => 'Email password reset link',
    'auth.forgot.return' => 'Or, return to',
    'auth.forgot.login' => 'log in',

    'auth.login.small.title' => 'Log in to your account',
    'auth.login.small.description' => 'Enter your email and password below to log in',
    'auth.login.title' => 'Log in',
    'auth.login.email' => 'Email address',
    'auth.login.password' => 'Password',
    'auth.login.forgot' => 'Forgot password?',
    'auth.login.remember' => 'Remember me',
    'auth.login.login' => 'Log in',
    'auth.login.dont' => 'Dont have an account?',
    'auth.login.signup' => 'Sign up',

    'auth.register.small.title' => 'Create an account',
    'auth.register.small.description' => 'Enter your details below to create your account',
    'auth.register.title' => 'Register',
    'auth.register.name' => 'Name',
    'auth.register.email' => 'Email address',
    'auth.register.password' => 'Password',
    'auth.register.password.confirm' => 'Confirm password',
    'auth.register.create' => 'Create account',
    'auth.register.already' => 'Already have an account?',
    'auth.register.login' => 'Log in',

    'auth.verifiy.small.title' => 'Verify email',
    'auth.verify.small.description' => 'Please verify your email address by clicking on the link we just emailed to you',
    'auth.verify.title' => 'Email verification',
    'auth.verify.description' => 'A new verification link has been sent to the email address you provided during registration',
    'auth.verify.resend' => 'Resend verification email',
    'auth.verify.logout' => 'Log out',

    'auth.reset.small.title' => 'Reset password',
    'auth.rese1t.small.description' => 'Please enter your new password below',
    'auth.reset.title' => 'Reset password',
    'auth.reset.email' => 'Email',
    'auth.reset.password' => 'Password',
    'auth.reset.password.confirm' => 'Confirm password',
    'auth.reset.button' => 'Reset password',

    'auth.complete.profile.title' => 'Complete Profile',
    'auth.complete.profile.label' => 'Complete your profile',
    'auth.complete.profile.text' => 'Please fill out your personal information to continue',
    'auth.complete.profile.age' => 'Age',
    'auth.complete.profile.height' => 'Height (Cm)',
    'auth.complete.profile.weight' => 'Weight (Kg)',
    'auth.complete.profile.phone' => 'Phone number',
    'auth.complete.profile.code' => 'Personal code',
    'auth.complete.profile.country' => 'Country',
    'auth.complete.profile.city' => 'City',
    'auth.complete.profile.portrait' => 'Portrait (optional)',
    'auth.complete.profile.save' => 'Save',

    'auth.complete.after.title' => 'Next Step',
    'auth.complete.after.label' => 'Do you own a business?',
    'auth.complete.after.text' => 'If yes, you can complete your business profile now or skip and continue to your dashboard',
    'auth.complete.after.yes' => 'Yes, i do',
    'auth.complete.after.no' => 'No, skip',

    'auth.complete.business.title' => 'Create Business',
    'auth.complete.business.label' => 'Create your business',
    'auth.complete.business.text' => 'Fill out your companys details to set up your business profile',
    'auth.complete.business.name' => 'Name',
    'auth.complete.business.industry' => 'Industry',
    'auth.complete.business.email' =>'Email',
    'auth.complete.business.phone' => 'Phone',
    'auth.complete.business.country' => 'Country',
    'auth.complete.business.city' => 'City',
    'auth.complete.business.address' => 'Address',
    'auth.complete.business.description' => 'Brief description',
    'auth.complete.business.logo' => 'Logo (optional)',
    'auth.complete.business.save' => 'Save',
    'auth.complete.business.cancel' => 'Cancel',
];
